sudo: required
dist: trusty

language: php

php:
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS platform;'

install:
  - composer install --prefer-source

script: phpunit

notifications:
  email: false
