language: php

php:
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - postgresql

before_install:
  - psql -c 'create database platform;' -U postgres

install:
  - composer install --prefer-source

script: vendor/bin/phpunit

notifications:
  email: false
